### ISSUE TITLE
will there be any issue when using babylon walk with babel/parse

### ISSUE THREAD

**Issue by chaitanya71998** [pugjs/babylon-walk#12]
i got confused with this statement in the readme `Lightweight AST traversal tools for Babylon ASTs`

**Comment by Narretz** [comment]
The output of babel (formerly babylon) is not estree conformant, so that's why it specifies this.

But you can actually use babel parser with the `estree` plugin, which produces estree compliant AST, and can be traversed by acorn-walk for example.
