### ISSUE TITLE
Any release plans?

### ISSUE THREAD

**Issue by wojtekmaj** [pugjs/babylon-walk#3]
I noticed there has been no release since 2016. However, you've updated your tool to Babel 7, and updating this dependency in parcel-bundler would cause a lot of legacy packages to be removed from node_modules.

**Comment by sukima** [comment]
Oh! that explains why nothing works! Damn, wish I had seen the issues first before wasting all that time trying to figure out why the docs are all wrong. 😞

**Comment by ForbesLindesay** [comment]
I've just taken over maintenance of this project and released an update as babel-walk.
